version: '3.5'

services:
  nginx:
    build: ./docker/nginx
    volumes:
      - "./app:/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-fpm
    ports:
      - "8010:80"

  php-fpm:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - "./app:/app"

  mysql:
    build: ./docker/mysql
    ports:
      - "3310:3306"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
