version: '3.5'

services:
  nginx:
    build: ./docker/nginx
    volumes:
      - "./app:/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-fpm
    ports:
      - "8010:80"

  php-fpm:
    build: ./docker/php
    volumes:
      - "./app:/app"

